config/routes.rb
Rails.application.routes.draw do
  controller :main do
    root :to => "main#home"
    get  '/help',               to: 'main#help'
    get  '/about',              to: 'main#about'
    get  '/contact',            to: 'main#contact'
  end
  get       '/signup',          to: 'users#new'
  post      '/signup',          to: 'users#create'
  get       '/signup',          to: 'users#edit'
  patch     '/signup',          to: 'users#update'
  resources :main
  resources :users
  resources :usergroups
  resources :classifications
  resources :coinbags
  resources :currencies
  #Reset password
  get       '/password',        to: 'sessions#password'
  post      '/password',        to: 'sessions#reset_pass'
  get       '/password_reset',  to: 'sessions#reset_password'
  post      '/password_reset',  to: 'sessions#reset_password_post'

  #User Settings
  get       '/settings',        to: 'settings#index'
  post      '/settings',        to: 'settings#save'

  #Global Settings
  get       '/global_settings', to: 'global_settings#index'
  post      '/global_settings', to: 'global_settings#save'

  #Administration
  get       '/administrators',  to: 'administrators#index'
  post      '/administrators',  to: 'administrators#exec'

  get       '/login',           to: 'sessions#new'
  post      '/login',           to: 'sessions#create'
  delete    '/logout',          to: 'sessions#destroy'
  get       '/users',           to: 'users#index'
  post      '/users',           to: 'users#create'
  get       '/users/new',       to: 'users#new'
  get       '/users/:id/edit',  to: 'users#edit'
  get       '/users/:id',       to: 'users#show'
  patch     '/users/:id',       to: 'users#update'
  put       '/users/:id',       to: 'users#update'
  delete    '/users/:id',       to: 'users#destroy'

  # To approve transactions
  get       '/tr_statements/approvals',   to: 'tr_statements#approvals'
  post      '/approvals',   to: 'tr_statements#approvals_run'

  resources :tr_statements

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #API ROUTES
  namespace 'api' do
    namespace 'v1' do
      resources :transactionin
      resources :transactionout
      resources :exchangein
      resources :exchangeout
    end
  end

  #REPORTS ROUTES
  get       '/treasuries',        to: 'treasuries#index'
  post      '/treasuries',        to: 'treasuries#filters'

  #MINERS MONITORING AND AUTOINSERT PAYMENTS
  get       '/miners',            to: 'miners#index'# via: :get
  put       '/miners',            to: 'miners#my_action'# via: :get
end

app/models/currency.rb
class Currency
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :currency, :type => String, :index => true, :uniq => true
  field :created_at, :type => Time
  field :created_by, :type => String
  field :changed_at, :type => Time
  field :changed_by, :type => String
  field :exch_symbol,:type => String
  field :exch_name,  :type => String
  field :exch_rate,  :type => Float
  field :cur_type,   :type => String

  #has_many :currency_defaults
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    if session[:user_id].to_s == ''
      flash[:notice] = "You must login to access the app..."
      redirect_to login_path
    end



    @currencies = Currency.all

  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:currency, :exch_rate, :exch_name, :exch_symbol)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_with(model: currency, local: true) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="st_input" border="0">
    <div class="field">
      <tr>
        <td><%= form.label :currency %></td>
        <td><%= form.text_field :currency %></td>
      </tr>
      <% if session[:admin].to_s != "[true]" %>
        <tr>
          <td><%= form.label 'Exchange Symbol' %></td>
          <td><%= form.text_field :exch_symbol, :disabled => true %></td>
        </tr>
        <tr>
          <td><%= form.label 'Exchange Name' %></td>
          <td><%= form.text_field :exch_name, :disabled => true %></td>
        </tr>
        <tr>
          <td><%= form.label 'Exchange Rate' %></td>
          <td><%= form.text_field :exch_rate, :disabled => true %></td>
        </tr>
        <tr>
          <td><%= form.label 'Kind of currency' %></td>
          <td><%= form.text_field :cur_type, :disabled => true %></td>
        </tr>
    <% else %>
        <tr>
          <td><%= form.label 'Exchange Symbol' %></td>
          <td><%= form.text_field :exch_symbol %></td>
        </tr>
        <tr>
          <td><%= form.label 'Exchange Name' %></td>
          <td><%= form.text_field :exch_name %></td>
        </tr>
        <tr>
          <td><%= form.label 'Exchange Rate' %></td>
          <td><%= form.text_field :exch_rate %></td>
        </tr>
        <tr>
          <td><%= form.label 'Kind of currency' %></td>
          <td><%= form.text_field :cur_type %></td>
        </tr>
    <% end %>
    </div>

    <div class="actions">
      <tr>
        <td><%= form.submit 'Submit', name: 'send', id: 'send', class: "btn btn-lg btn-primary", data: { disable_with: "Please wait.." } %></td>
        <td><%= link_to 'Back', currencies_path, class: "btn btn-lg btn-primary" %></td>
      </tr>
    </div>
  </table>
<% end %>

app/views/currencies/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Currency</h1>

    <%= render 'form', currency: @currency %>
  </div>
</div>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Currencies</h1>
<body class='currencies_body' id="Currenciesbody" data-controller="<%= controller.controller_name %>">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table id="currencies">
        <thead>
          <tr>
            <th>Currency</th>
            <th>Exchange Symbol</th>
            <th>Exchange Name</th>
            <th>Exchange Rate</th>
            <th style="width:5px;"></th>
            <th style="width:5px;"></th>
            <th style="width:5px;"></th>
          </tr>
        </thead>

        <tbody>
          <% @currencies.each do |currency| %>
            <tr>
              <td><%= currency.currency %></td>
              <td><%= currency.exch_symbol %></td>
              <td><%= currency.exch_name %></td>
              <td><%= currency.exch_rate %></td>
              <td><%= link_to 'Show', currency %></td>
              <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
              <td><%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Currency', new_currency_path, class: "btn btn-lg btn-primary" %>

    </div>
  </div>
</body>

app/views/currencies/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Currency</h1>

    <%= render 'form', currency: @currency, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/currencies/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p id="notice"><%= notice %></p>

    <table>
      <tr>
        <th><strong>Currency:</strong></th>
        <th><%= @currency.currency %></th>
      </tr>
      <tr>
        <th><strong>Exchange Symbol:</strong></th>
        <th><%= @currency.exch_symbol %></th>
      </tr>
      <tr>
        <th><strong>Exchange Name:</strong></th>
        <th><%= @currency.exch_name %></th>
      </tr>
      <tr>
        <th><strong>Exchange Rate:</strong></th>
        <th><%= @currency.exch_rate %></th>
      </tr>
    </table>

    <%= link_to 'Edit', edit_currency_path(@currency), class: "btn btn-lg btn-primary" %>
    <%= link_to 'Back', currencies_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>