config/routes.rb
Rails.application.routes.draw do
  controller :main do
    root :to => "main#home"
    get  '/help',               to: 'main#help'
    get  '/about',              to: 'main#about'
    get  '/contact',            to: 'main#contact'
  end
  get       '/signup',          to: 'users#new'
  post      '/signup',          to: 'users#create'
  get       '/signup',          to: 'users#edit'
  patch     '/signup',          to: 'users#update'
  resources :main
  resources :users
  resources :usergroups
  resources :classifications
  resources :coinbags
  resources :currencies
  #Reset password
  get       '/password',        to: 'sessions#password'
  post      '/password',        to: 'sessions#reset_pass'
  get       '/password_reset',  to: 'sessions#reset_password'
  post      '/password_reset',  to: 'sessions#reset_password_post'

  #User Settings
  get       '/settings',        to: 'settings#index'
  post      '/settings',        to: 'settings#save'

  #Global Settings
  get       '/global_settings', to: 'global_settings#index'
  post      '/global_settings', to: 'global_settings#save'

  #Administration
  get       '/administrators',  to: 'administrators#index'
  post      '/administrators',  to: 'administrators#exec'

  get       '/login',           to: 'sessions#new'
  post      '/login',           to: 'sessions#create'
  delete    '/logout',          to: 'sessions#destroy'
  get       '/users',           to: 'users#index'
  post      '/users',           to: 'users#create'
  get       '/users/new',       to: 'users#new'
  get       '/users/:id/edit',  to: 'users#edit'
  get       '/users/:id',       to: 'users#show'
  patch     '/users/:id',       to: 'users#update'
  put       '/users/:id',       to: 'users#update'
  delete    '/users/:id',       to: 'users#destroy'

  # To approve transactions
  get       '/tr_statements/approvals',   to: 'tr_statements#approvals'
  post      '/approvals',   to: 'tr_statements#approvals_run'

  resources :tr_statements

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #API ROUTES
  namespace 'api' do
    namespace 'v1' do
      resources :transactionin
      resources :transactionout
      resources :exchangein
      resources :exchangeout
    end
  end

  #REPORTS ROUTES
  get       '/treasuries',        to: 'treasuries#index'
  post      '/treasuries',        to: 'treasuries#filters'

  #MINERS MONITORING AND AUTOINSERT PAYMENTS
  get       '/miners',            to: 'miners#index'# via: :get
  put       '/miners',            to: 'miners#my_action'# via: :get
end

app/models/user.rb
class User
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps
  has_many :coinbag

  before_save { self.email = email.downcase }
  validates :password_digest,  presence: true, length: { minimum: 8 }
  validates :username,  presence: true, length: { minimum: 5, maximum: 20 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,  presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
  validates :nickname,  presence: true, uniqueness: true
  #validates :status,  presence: true

  def email=(value)
    super(value.strip.downcase)
  end

  field :username, :type => String, :index => true, :uniq => true
  field :password_digest, :type => String, :required => true
  field :surname, :type => String, :required => true
  field :givenname, :type => String, :required => true
  field :nickname, :type => String, :uniq => true, :required => true
  field :birthdate_time, :type => Time
  field :email, :type => String, :uniq => true, :required => true
  field :spreadsheet_link, :type => String
  field :sheet_name, :type => String
  field :verified, :type => Boolean 
  field :admin, :type => Boolean #User is app administrator?
  field :group, :type => String, :required => true #used to define users and teams
  field :status, :type => String, :required => true #Status of user in app
  field :profile, :type => String, :required => true #Used to create users group on app

  #has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # Goggle drive class
  require './app/models/google_synch2'

  # GET /users
  # GET /users.json
  def index
    if session[:user_id].to_s == ''
      flash[:notice] = "You must login to access the app..."
      redirect_to login_path
    end

    respond_to do |format|
      format.html
      format.json { render json: UsersDatatable.new(view_context) }
    end

    #@users = User.all
    #@users = @users.order(:givenname)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    #update global variable to send the google key to google API class
    $user_google_key = @user.spreadsheet_link
    #update global variable to send the google Sheet Name to google API class
    $user_google_sheet_name = @user.sheet_name

    #Call Google spreadsheet connection class
    @google_synch = Google_synch_a.new



    @kind = 'edit'

  end

  # GET /users/new
  def new
    @user = User.new
    @kind = 'new'
    @profile = Usergroup.all
    @profile = @profile.order('group_name')
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @kind = 'edit'
    @profile = Usergroup.all
    @profile = @profile.order('group_name')
  end

  # POST /users
  # POST /users.json
  def create
    data_manipulation

    salt  = 'CCEKvUgNbXByO6eAp2pgb56Nur/E16tHA1cYY2Ofai8='
    key   = ActiveSupport::KeyGenerator.new('password').generate_key(salt, 32)
    crypt = ActiveSupport::MessageEncryptor.new(key)
    encrypted_data = crypt.encrypt_and_sign(params[:user][:"password_digest"], purpose: :login)
    params[:user][:password_digest] = encrypted_data

    if params[:user][:id] == ''
      params[:user][:id] = unique_identifier = SecureRandom.hex(15)
    end

    @user = User.new(user_params)

    if session[:user_id]
      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: "User was successfully created.!" }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_now
        UserMailer.with(user: @user).approve_user_email.deliver_now
        flash[:success] = "Welcome to the Veda Treasury App!"
        redirect_to login_path #@user
        #format.json { render :show, status: :created, location: @user }
      else
        render :new
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    data_manipulation

    @user = User.find(params[:user][:"id"])
    @verified = User.where(id: @user.id).map(&:verified)*","
    if @user.update(user_params)

      if @verified == 'false' && params[:user][:verified] == '1'
        UserMailer.with(user: @user).approved_user.deliver_now
      end
      flash[:success] = "User was successfully updated.!"
      redirect_to @user
      #format.json { render :show, status: :ok, location: @user }
    else
      render :edit
      #format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if @kind == 'edit'
        @user = User.find(params[:user][:"id"])
      elsif @kind == 'new' || @kind == 'show'
        @user = User.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:profile, :status, :group, :verified, :admin, :id, :username, :password_digest, :surname, :givenname, :nickname, :birthdate_time, :spreadsheet_link, :email, :sheet_name)
    end

    #function to manipulate form data
    def data_manipulation
      #params[:user][:birthdate_time] = Time.new(params[:user][:"birthdate_time(1i)"].to_i,params[:user][:"birthdate_time(2i)"].to_i,params[:user][:"birthdate_time(3i)"].to_i,params[:user][:"birthdate_time(4i)"].to_i,params[:user][:"birthdate_time(5i)"].to_i,0,'+00:00')
      #params[:user].delete(:"birthdate_time(1i)")
      #params[:user].delete(:"birthdate_time(2i)")
      #params[:user].delete(:"birthdate_time(3i)")
      #params[:user].delete(:"birthdate_time(4i)")
      #params[:user].delete(:"birthdate_time(5i)")
      params[:user][:email] = params[:user][:"email"].downcase
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.nickname, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, url: signup_path) do |form| %>
  <% if user.errors.any? %>
  <%= render 'shared/error_messages' %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, class: 'form-control' %>
  </div>

  <% if @kind == 'new' %>
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field  :password_digest, class: 'form-control' %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :givenname %>
    <%= form.text_field :givenname, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, class: 'form-control' %>
  </div>

<!--
  <div class="field">
    <%= form.label :'Birthdate and Time' %>
    <%= form.datetime_select :birthdate_time, :start_year => 1900, class: 'form-control-datetime' %>
  </div>
-->

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label "#{:kind} of user" %>
    <%= form.select :group, ['', 'Member','Team','World'], class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label "User #{:status}" %>
    <%= form.select :status, ['Active','Inactive'], class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label "User #{:profile}" %>
    <%= form.collection_select :profile, @profile, :id, :group_name, include_blank: true %>
  </div>

<!--
  <div class="field">
    %= form.label :spreadsheet_link %>
    %= form.text_field :spreadsheet_link, class: 'form-control' %>
  </div>

  <div class="field">
    %= form.label :sheet_name %>
    %= form.text_field :sheet_name, class: 'form-control' %>
  </div>
-->
  <% if @kind != 'new' %>
    <%= form.hidden_field :id, value: params[:id].to_s %>
  <% else %>
    <%= form.hidden_field :id, value: @user.id %>
  <% end %>

  <% if session[:admin].to_s == "[true]" and session[:user_id] != '' %>
    <table class="user_administrator" border="0">
      <div class="Boolean_Class">
        <tr>
          <td><%= form.label 'User Verified?', class: 'Check_Boolean_Class' %></td>
          <td><span style="display:inline-block; width: 10px;"></span></td>
          <td><%= form.check_box :verified, class: 'Label_Boolean_Class' %></td>
        </tr>
        <tr>
          <td><span style="display:block; height: 10px;"></span></td>
        </tr>
      </div>

      <div class="Boolean_Class">
        <tr>
          <td><%= form.label "Administrator?", class: 'Label_Boolean_Class' %></td>
          <td></td>
          <td><%= form.check_box :admin, class: 'Check_Boolean_Class' %></td>
        </tr>
        <tr>
          <td><span style="display:block; height: 10px;"></span></td>
        </tr>
      </div>
    </table>
  <% end %>

  <table>
      <div class="actions">
        <tr>
          <td><%= form.submit "Submit", class: "btn btn-lg btn-primary", data: { disable_with: "Please wait.." }  %></td>
          <% if session[:admin].to_s == '[true]' %>
            <td><%= link_to 'Back', users_path, class: "btn btn-lg btn-primary" %></td>
          <% end %>
        </tr>
      </div>
  </table>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', user: @user %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>

<body class='users_body' id="Usersbody">
  <div>
    <div>
      <table id="users" class="display" style="text-align: left; width: 100%;" data-source="<%= users_url(format: "json") %>">
        <thead>
          <tr>
            <th>Details</th>
            <th>Username</th>
            <th>Nickname</th>
            <th>Email</th>
            <th>Status</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>

      <br>

      <%= link_to 'New User', new_user_path, class: "btn btn-lg btn-primary" %>

    </div>
  </div>
</body>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <td><%= render 'form', user: @user %></td>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.surname + ', ' + @user.givenname) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%=  @user.surname + ', ' + @user.givenname %>
        </h1>
      </section>
    </aside>
    <p>
      <strong>Username:</strong>
      <%= @user.username %>
    </p>

    <p>
      <strong>Surname:</strong>
      <%= @user.surname %>
    </p>

    <p>
      <strong>Givenname:</strong>
      <%= @user.givenname %>
    </p>

    <p>
      <strong>Nickname:</strong>
      <%= @user.nickname %>
    </p>

<!--
    <p>
      <strong>Birthdate time:</strong>
      <%= @user.birthdate_time %>
    </p>
-->
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @user.status %>
    </p>

    <p>
      <strong>Kind of user:</strong>
      <%= @user.group %>
    </p>

    <% @kind = 'edit' %>
    <td><%= link_to 'Edit', edit_user_path(@user), class: "btn btn-lg btn-primary" %></td>
    <% if session[:admin].to_s == '[true]' %>
      <td><%= link_to 'Back', users_path, class: "btn btn-lg btn-primary" %></td>
    <% end %>
  </div>
</div>
<h2>User google spreadsheet coinlog</h2>

<br>