config/routes.rb
Rails.application.routes.draw do
  controller :main do
    root :to => "main#home"
    get  '/help',               to: 'main#help'
    get  '/about',              to: 'main#about'
    get  '/contact',            to: 'main#contact'
  end
  get       '/signup',          to: 'users#new'
  post      '/signup',          to: 'users#create'
  get       '/signup',          to: 'users#edit'
  patch     '/signup',          to: 'users#update'
  resources :main
  resources :users
  resources :usergroups
  resources :classifications
  resources :coinbags
  resources :currencies
  #Reset password
  get       '/password',        to: 'sessions#password'
  post      '/password',        to: 'sessions#reset_pass'
  get       '/password_reset',  to: 'sessions#reset_password'
  post      '/password_reset',  to: 'sessions#reset_password_post'

  #User Settings
  get       '/settings',        to: 'settings#index'
  post      '/settings',        to: 'settings#save'

  #Global Settings
  get       '/global_settings', to: 'global_settings#index'
  post      '/global_settings', to: 'global_settings#save'

  #Administration
  get       '/administrators',  to: 'administrators#index'
  post      '/administrators',  to: 'administrators#exec'

  get       '/login',           to: 'sessions#new'
  post      '/login',           to: 'sessions#create'
  delete    '/logout',          to: 'sessions#destroy'
  get       '/users',           to: 'users#index'
  post      '/users',           to: 'users#create'
  get       '/users/new',       to: 'users#new'
  get       '/users/:id/edit',  to: 'users#edit'
  get       '/users/:id',       to: 'users#show'
  patch     '/users/:id',       to: 'users#update'
  put       '/users/:id',       to: 'users#update'
  delete    '/users/:id',       to: 'users#destroy'

  # To approve transactions
  get       '/tr_statements/approvals',   to: 'tr_statements#approvals'
  post      '/approvals',   to: 'tr_statements#approvals_run'

  resources :tr_statements

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #API ROUTES
  namespace 'api' do
    namespace 'v1' do
      resources :transactionin
      resources :transactionout
      resources :exchangein
      resources :exchangeout
    end
  end

  #REPORTS ROUTES
  get       '/treasuries',        to: 'treasuries#index'
  post      '/treasuries',        to: 'treasuries#filters'

  #MINERS MONITORING AND AUTOINSERT PAYMENTS
  get       '/miners',            to: 'miners#index'# via: :get
  put       '/miners',            to: 'miners#my_action'# via: :get
end

app/models/classification.rb
class Classification
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :classification, :type => String, :uniq => true
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  before_action :set_classification, only: [:show, :edit, :update, :destroy]

  # GET /reasons
  # GET /reasons.json
  def index
    if session[:user_id].to_s == ''
      flash[:notice] = "You must login to access the app..."
      redirect_to login_path
    end    
    @classifications = Classification.all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @classification = Classification.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @classification = Classification.new(classification_params)

    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, notice: 'Classification was successfully created.' }
        format.json { render :show, status: :created, location: @classification }
      else
        format.html { render :new }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @classification.update(classification_params)
        format.html { redirect_to @classification, notice: 'Classification was successfully updated.' }
        format.json { render :show, status: :ok, location: @classification }
      else
        format.html { render :edit }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @classification.destroy
    respond_to do |format|
      format.html { redirect_to classifications_url, notice: 'Classification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classification
      @classification = Classification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classification_params
      params.require(:classification).permit(:classification)
    end
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/classifications/_form.html.erb
<%= form_with(model: classification, local: true) do |form| %>
  <% if classification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classification.errors.count, "error") %> prohibited this classification from being saved:</h2>

      <ul>
      <% classification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="st_input" border="0">
    <div class="field">
      <tr>
        <td><%= form.label "Category" %></td>
        <td><%= form.text_field :classification %></td>
      </tr>
    </div>

    <div class="actions">
      <tr>
        <td><%= form.submit 'Submit', name: 'send', id: 'send', class: "btn btn-lg btn-primary", data: { disable_with: "Please wait.." } %></td>
        <td><%= link_to 'Back', classifications_path, class: "btn btn-lg btn-primary" %></td>
      </tr>
    </div>
  </table>
<% end %>

app/views/classifications/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Veda Category</h1>
    <%= render 'form', classification: @classification %>
  </div>
</div>

app/views/classifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>
<body class='classifications_body' id="Classificationsbody" data-controller="<%= controller.controller_name %>">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table id="classifications">
        <thead>
          <tr>
            <th>Categories</th>
            <th style="width:5px;"></th>
            <th style="width:5px;"></th>
            <th style="width:5px;"></th>
          </tr>
        </thead>

        <tbody>
          <% @classifications.each do |classification| %>
            <tr>
              <td><%= classification.classification %></td>
              <td><%= link_to 'Show', classification %></td>
              <td><%= link_to 'Edit', edit_classification_path(classification) %></td>
              <td><%= link_to 'Destroy', classification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Classification', new_classification_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</body>

app/views/classifications/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Category</h1>
    <%= render 'form', classification: @classification, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/classifications/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Category:</strong>
      <%= @classification.classification %>
    </p>
    <td><%= link_to 'Edit', edit_classification_path(@classification), class: "btn btn-lg btn-primary" %> </td>
    <td><%= link_to 'Back', classifications_path, class: "btn btn-lg btn-primary" %> </td>

  </div>
</div>