config/routes.rb
Rails.application.routes.draw do
  controller :main do
    root :to => "main#home"
    get  '/help',               to: 'main#help'
    get  '/about',              to: 'main#about'
    get  '/contact',            to: 'main#contact'
  end
  get       '/signup',          to: 'users#new'
  post      '/signup',          to: 'users#create'
  get       '/signup',          to: 'users#edit'
  patch     '/signup',          to: 'users#update'
  resources :main
  resources :users
  resources :usergroups
  resources :classifications
  resources :coinbags
  resources :currencies
  #Reset password
  get       '/password',        to: 'sessions#password'
  post      '/password',        to: 'sessions#reset_pass'
  get       '/password_reset',  to: 'sessions#reset_password'
  post      '/password_reset',  to: 'sessions#reset_password_post'

  #User Settings
  get       '/settings',        to: 'settings#index'
  post      '/settings',        to: 'settings#save'

  #Global Settings
  get       '/global_settings', to: 'global_settings#index'
  post      '/global_settings', to: 'global_settings#save'

  #Administration
  get       '/administrators',  to: 'administrators#index'
  post      '/administrators',  to: 'administrators#exec'

  get       '/login',           to: 'sessions#new'
  post      '/login',           to: 'sessions#create'
  delete    '/logout',          to: 'sessions#destroy'
  get       '/users',           to: 'users#index'
  post      '/users',           to: 'users#create'
  get       '/users/new',       to: 'users#new'
  get       '/users/:id/edit',  to: 'users#edit'
  get       '/users/:id',       to: 'users#show'
  patch     '/users/:id',       to: 'users#update'
  put       '/users/:id',       to: 'users#update'
  delete    '/users/:id',       to: 'users#destroy'

  # To approve transactions
  get       '/tr_statements/approvals',   to: 'tr_statements#approvals'
  post      '/approvals',   to: 'tr_statements#approvals_run'

  resources :tr_statements

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #API ROUTES
  namespace 'api' do
    namespace 'v1' do
      resources :transactionin
      resources :transactionout
      resources :exchangein
      resources :exchangeout
    end
  end

  #REPORTS ROUTES
  get       '/treasuries',        to: 'treasuries#index'
  post      '/treasuries',        to: 'treasuries#filters'

  #MINERS MONITORING AND AUTOINSERT PAYMENTS
  get       '/miners',            to: 'miners#index'# via: :get
  put       '/miners',            to: 'miners#my_action'# via: :get
end

app/models/coinbag.rb
class Coinbag
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :coinbag, :type => String, :validates => {:uniqueness => {:scope => :user_id}}
  field :user_id, :type => String
end

app/controllers/coinbags_controller.rb
class CoinbagsController < ApplicationController
  before_action :set_coinbag, only: [:show, :edit, :update, :destroy]

  # GET /coinbags
  # GET /coinbags.json
  def index
    if session[:user_id].to_s == ''
      flash[:notice] = "You must login to access the app..."
      redirect_to login_path
    end
    if session[:admin].to_s == "[true]" and session[:user_id] != ''
      @coinbags = Coinbag.all
      @coinbags = @coinbags.order('user_id', 'coinbag')
    else
      @coinbags = Coinbag.where(user_id: session[:user_id])
      @coinbags = @coinbags.order('coinbag')
    end
  end

  # GET /coinbags/1
  # GET /coinbags/1.json
  def show
  end

  # GET /coinbags/new
  def new
    @type = 'NEW'
    @coinbag = Coinbag.new
  end

  # GET /coinbags/1/edit
  def edit
    @type = 'EDIT'
  end

  # POST /coinbags
  # POST /coinbags.json
  def create
    @coinbag = Coinbag.new(coinbag_params)

    respond_to do |format|
      if @coinbag.save
        format.html { redirect_to @coinbag, notice: 'Coinbag was successfully created.' }
        format.json { render :show, status: :created, location: @coinbag }
      else
        format.html { render :new }
        format.json { render json: @coinbag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coinbags/1
  # PATCH/PUT /coinbags/1.json
  def update
    respond_to do |format|
      if @coinbag.update(coinbag_params)
        format.html { redirect_to @coinbag, notice: 'Coinbag was successfully updated.' }
        format.json { render :show, status: :ok, location: @coinbag }
      else
        format.html { render :edit }
        format.json { render json: @coinbag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coinbags/1
  # DELETE /coinbags/1.json
  def destroy
    @coinbag.destroy
    respond_to do |format|
      format.html { redirect_to coinbags_url, notice: 'Coinbag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Select coinbags from user in transaction form when select user combobox
  def user_coinbags
    coinbag_id = params[:id].to_i
    coinbags = Coinbag.where(:id => coinbag_id)
    cbag = []
    coinbags.each do |coinbag|
      cbag << {:id => coinbag.id, :n => coinbag.coinbag}
    end
    cbag << {id => "qiyetuqtye8", :n => "TESTE"}
    render :json => {:cbag => cbag.compact}.as_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coinbag
      @coinbag = Coinbag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coinbag_params
      params.require(:coinbag).permit(:coinbag, :user_id)
    end
end

app/helpers/coinbags_helper.rb
module CoinbagsHelper
end

app/views/coinbags/_form.html.erb
<%= form_with(model: @coinbag, local: true) do |form| %>
  <% if @coinbag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coinbag.errors.count, "error") %> prohibited this coinbag from being saved:</h2>

      <ul>
      <% @coinbag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="st_input" border="0">
    <div class="field">
      <tr>
        <td><%= form.label :coinbag %></td>
        <td><%= form.text_field :coinbag %></td>
      </tr>
    </div>

    <% if session[:admin] == [true] %>
      <div class="field">
        <tr>
          <td><%= form.label "User" %></td>
          <% if @type == 'NEW' %>
            <td><%= form.collection_select :user_id, User.all, :id, :username, selected: session[:user_id] %>
          <% else %>
            <td><%= form.collection_select :user_id, User.all, :id, :username %>
          <% end %>
          <div id="CTR_coinbag_dest" class="CTR_form"><%= @action == 'NEW' && '*' || '' %></div></td>
        </tr>
      </div>
    <% else %>
      <td><%= form.hidden_field :user_id, :value => session[:user_id] %></td>
    <% end %>

    <div class="actions">
      <tr>
        <td><%= form.submit "Submit", class: "btn btn-lg btn-primary", data: { disable_with: "Please wait.." } %></td>
        <td><%= link_to 'Back', coinbags_path, class: "btn btn-lg btn-primary" %></td>
      </tr>
    </div>
  </table>
<% end %>

app/views/coinbags/create.js.erb
<% if @coinbag.valid? %>
  $('#dialog-form').dialog('close');
  $('#dialog-form').remove();

  // Add the newly created article to the table
  $('table tbody').append('<%= j render(@coinbag) %>');
<% else %>
  // Validation failed, re-render the form showing the errors
  $('#dialog-form').html('<%=j render("coinbags/form") %>')
<% end %>

app/views/coinbags/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Coinbag</h1>

    <%= render 'form', coinbag: @coinbag %>
  </div>
</div>

app/views/coinbags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coinbags</h1>
<body class='coinbags_body' id="Coinbagsbody" data-controller="<%= controller.controller_name %>">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table id="coinbags">
        <thead>
          <tr>
            <th>Coinbag</th>
            <th>User coinbag</th>
            <th style="width:5px;"></th>
            <th style="width:5px;"></th>
            <th style="width:5px;"></th>
          </tr>
        </thead>

        <tbody>
          <% @coinbags.each do |coinbag| %>
            <tr>
              <td><%= coinbag.coinbag %></td>
              <td><%= User.where(id: coinbag.user_id).map(&:nickname)*",".to_s %></td>
              <td><%= link_to 'Show', coinbag %></td>
              <td><%= link_to 'Edit', edit_coinbag_path(coinbag) %></td>
              <td><%= link_to 'Destroy', coinbag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>

      <%= link_to 'New Coinbag', new_coinbag_path, id: "create_coinbag", class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</body>

app/views/coinbags/new.html.erb
<% provide(:title, 'Coinbag') %>
<% provide(:button_text, 'Create Coinbag') %>
<h1>New Coinbag</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <td><%= render 'form', coinbag: @coinbag %></td>
  </div>
</div>

app/views/coinbags/new.js.erb
<%= render("form") %>

app/views/coinbags/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Coinbag:</strong>
      <%= @coinbag.coinbag %>
    </p>

    <%= link_to 'Edit', edit_coinbag_path(@coinbag), class: "btn btn-lg btn-primary" %> |
    <%= link_to 'Back', coinbags_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>